[theme]
base = "light"
primaryColor = "#5B124D"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"

[server]
headless = true
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false
maxMessageSize = 500

[global]
maxCachedMessageAge = 0
developmentMode = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false