[[pages]]
path = "main.py"
name = "Start"
icon = ""

[[pages]]
path = "pages/steg1.py"
name = "Steg 1"
icon = ""

[[pages]]
path = "pages/steg2.py"
name = "Steg 2"
icon = ""

[[pages]]
path = "pages/steg3.py"
name = "Steg 3"
icon = ""

[[pages]]
path = "pages/steg4.py"
name = "Steg 4"
icon = ""